sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

env:
  global:
    - secure: Ss/xw4Jfdy3Qw3BCDEf/NYxLeV1CBymLDDIEjeH4TuiZ3wnOY8BjX2mwp35HxhDL25GgrjyGvZt5wWojRBh6SC/8pPj+tIIuoomVGM8dj67iNVaGDOVUdnS+KtBfPIADI5QrPYzoLUiZBq6t3zElCC31eHB93TLQohZrh70CALdYvHONnSp29eCeYucQ8fBlYW/EoWWdly9S/FA3F17ZxdmN/TJH28z9w3pBYMOXeqg0et/p6CBMgJYF/K0GCIQ8cwlxAZtpXeOIYJQOBdhmOeEPxJI8/XRPyXgsCaX1YSAn2e8PqlNymR3TzAAto5ZNqywT9odoyMYjY/lTg73ZIi5D/pV1MKhaNmZ7Mfsw9Nxz9hLSk7wRIMP+Rr5CofJX93upwN9H4vdHf3ecp9sNgNyBSkICCnuqoC3chPRmRgkuQusuw9+wxVsNQc7keFd5pkUXBXo55qmSyFktfX3iQp71vEdxlZDEj+0B3G5e0pnCTIg3ynqH/osJkeh57zVhImGnY10kmlXHEOL9HJ0EHe9Ww5Chixahm1FR6FC7zRL9nXHoS0xM3WfKow6++y1kGSD3v+YZtNNWheST3SjuacBh651ZpLDCEkUa5INvecxVaGCkrvhxqacK6oW2x7kEvjqI02W0b3AaDVM9wfRXrUYDX1/b3jjfYzcU7zH8Zf0=
