sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

env:
  - FANART_KEY=bd2753f04538b01479e39e695308b921
